title:             FitHome
email:             your-email@example.com
description:       Trim the Fat from your Electricity Bills.
author:            HappyDay
baseurl:           "FitHome_web"


# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
