title:             FitHome
email:             your-email@example.com
description:       Trim the Fat from your Electricity Bills.<br>Help Combat Climate Change.
author:            HappyDay
baseurl:           ""

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
